apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: storefront-obs-backend
  namespace: storefront-obs
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: storefront-obs-backend
  endpoints:
    - targetPort: 8000
      path: /prometheus-metrics
      interval: 15s
